ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:openwrt-fwsel: https://firmware-selector.openwrt.org[OpenWRT Firmware Selector]

= Personal customizable OpenWRT x86/64 Image Builder

This repository hosts GitHub actions for on-demand builds of customized OpenWRT x86/64 images.
This is an unofficial companion to the official {openwrt-fwsel} with additional features that targets only x86/64 architecture.

Want a OpenWRT x86/64 image with your packages/files/scripts?

It's easy as 1-2-3:

. Fork this repo.
. Run `Build Image` action with your options.
. Download built image from the `Artifacts` section of the action run.

By default all public repositories have 90 days of retention for artifacts, so you can always re-download your images.
This is another advantage of this builder over the official {openwrt-fwsel} which has no retention at all.

== Motivation

While an official {openwrt-fwsel} provides a good for most cases customizable image builder,
it has a limitation on a rootfs partition size which is 104 MByte.
It's a huge limitation on how many packages you can put into an image.

This is a "no-go" situation if your aim is to get a ready-to-go image with a lot of packages for a router and app server system running on x86-64 architecture.
This image builder removes these limits and also provides on-demand builds.

**Goals are:**

. Provide on-demand builds of customized and ready-to-use OpenWRT x86/64 images of `.img` and `.qcow2` formats.
. Provide an offsite place for downloads of customized images based on **stable** OpenWRT releases.
. Provide a forkable repository (template) for building personalized OpenWRT x86/64 images.

**Non-goals are:**

. Support architectures other than x86/64. Custom images for embedded devices with heavily constrained resources can be easily built using the official {openwrt-fwsel}.
. Create a replacement for the official OpenWRT image builder.

== Images

The builder produces only images with the following characteristics:

Partition format:: ext4
Image type:: combined EFI `.img` and `.qcow2`
Architecture:: Generic x86/64

[NOTE]
For image type details and "how to install", check an https://openwrt.org/docs/guide-user/installation/openwrt_x86[official page].

=== Files and scripts

If you need files/scripts built into the image, you can place them in `files/` directory of this repository.
The builder will copy them to the root of the image.
A good example would be a https://openwrt.org/docs/guide-developer/uci-defaults[UCI defaults] a first-boot scripts.
For instance creating a `files/etc/uci-defaults/99-mynetwork` script that contains your custom network configuration will end up in `/etc/uci-defaults/99-mynetwork` of a rootfs and will be executed on a first boot.

== New features

The builder is mostly feature-complete as it's gained current goals.
Currently, there are no plans to add new features, as almost all goals are already met.
Features may be added once the OpenWRT image builder adds new capabilities.

== License

MIT License.
