ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:openwrt-fwsel: https://firmware-selector.openwrt.org[OpenWRT Firmware Selector]
:url-artifact-retention: https://docs.github.com/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization
:url-rootfs-size: https://github.com/openwrt/openwrt/blob/099633be82ee8a75a2f271b90f3a07e6e2c01ffc/config/Config-images.in#L339
:url-install-x86: https://openwrt.org/docs/guide-user/installation/openwrt_x86
:url-uci-defaults: https://openwrt.org/docs/guide-developer/uci-defaults

= Personal customizable OpenWRT x86/64 Image Builder

This repository hosts GitHub Actions for on-demand builds of customised OpenWRT x86/64 images.
This is an unofficial companion to the official {openwrt-fwsel} with additional features targeting only x86/64 architecture.

Want a OpenWRT x86/64 image with your packages/files/scripts?

It's easy as 1-2-3:

. Fork this repo.
. Run `Build Image` action with your options.
. Download the image from the Action's `Artifacts` section.

**Bonus**:
GitHub has {url-artifact-retention}[a configurable retention period] for artifacts, so you can always re-download your images during this period.

Read details below.

== Motivation

While the official {openwrt-fwsel} provides a good (for most cases) customizable image builder,
it has a limitation (as of v24.10) on a rootfs partition size which is {url-rootfs-size}[104 MByte].
Also, it doesn't support building QEMU images in a qcow2 format.

In essence, the official builder is often a "no-go" solution for x86/64 images since such hardware is usually picked to run a bunch of resource-demanding apps.
This often implies that the initial image may need a bunch of heavyweight preinstalled packages, like Docker,
so images easily exceed the default rootfs size.

This image builder removes these limitations and allows you to build truly customised images, while GitHub provides on-demand build runners and {url-artifact-retention}[temporary storage] for built images.

**Goals:**

. Provide on-demand builds of customized and ready-to-use OpenWRT x86/64 images in `.img` and `.qcow2` formats.
. Provide an offsite place for downloads of customized images based on **stable** OpenWRT releases.
. Provide a forkable repository (template) for building personalized OpenWRT x86/64 images.

**Not goals:**

. Support architectures other than x86/64. Custom images for embedded devices with heavily constrained resources can be easily built using the official {openwrt-fwsel}.
. Support of unstable release builds.
. Create a replacement for the official OpenWRT image builder.

== Instructions

After forking the repository:

image::doc/run-action-instruction.avif[width=50%]

. Go to the "Actions" of _your forked repo_.
. Select "Build Image" action.
. Click "Run workflow" button.
. Fill required fields.
. Run the workflow.
. Once the action finished running, open the last "Build image" run to view and download artifacts.

== Images

The builder produces only images of the following type:

Partition format:: ext4
Image type:: combined EFI `.img` and `.qcow2`
Architecture:: Generic x86/64

[NOTE]
For image type details and "how to install", check {url-install-x86}[the official documentation].

=== Adding files/scripts to the image

If you need files/scripts built into the image, you can place them in `files/` directory of your forked repository.
The builder will copy them to the root of the image.

A good example would be a {url-uci-defaults}[UCI defaults], a first-boot scripts.
For instance, adding a `files/etc/uci-defaults/99-mynetwork` script to this repo containing a custom network configuration, the file will appear in `/etc/uci-defaults/99-mynetwork` of a rootfs, and as such it will be executed on a first boot.

== New features

There are no plans to add new features, as all goals are already met so far.
Features may be added once the official image builder adds new capabilities.

== License

MIT License.
