name: OpenWRT Release Checker
on:
  workflow_dispatch:
  schedule:
    - cron: '20 4 * * *'  # Every day at 04:20 UTC
jobs:
  release_checker:
    name: Check new releases
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Check versions
      id: version_check
      run: |
        GH_TAG_OPTS="--exclude-pre-releases --limit 1 --json tagName --jq .[].tagName"
        OPENWRT_VER="$(gh release list --repo openwrt/openwrt $GH_TAG_OPTS)"
        IMAGE_VER="$(gh release list $GH_TAG_OPTS)"

        if [[ -z "$IMAGE_VER" ]]; then
          IMAGE_VER="none"
          echo "No image releases found. Image will be built for the latest OpenWRT version."
        fi

        echo "Latest versions:"
        echo "    OpenWRT=$OPENWRT_VER"
        echo "    Image=$IMAGE_VER"

        if [[ "$OPENWRT_VER" == "$IMAGE_VER" ]]; then
          echo "No new OpenWRT release found. Exiting."
          exit 0
        else
          echo "New OpenWRT release found: $OPENWRT_VER"
        fi

        echo "Scheduling a build for $OPENWRT_VER."
        gh workflow run release-image.yaml -f version=${OPENWRT_VER/#v/}