name: Release Image
on:
  workflow_dispatch:
    inputs:
      version:
        description: "A bare version string without 'v' prefix"
        required: true
        type: string
      tag:
        description: "A tag of release as it will be created, with 'v' prefix"
        required: true
        type: string

jobs:
  builder:
    name: Image builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download image builder
        id: download_image_builder
        run: |
          wget "https://downloads.openwrt.org/releases/${{ inputs.version }}/targets/x86/64/openwrt-imagebuilder-${{ inputs.version }}-x86-64.Linux-x86_64.tar.zst"
          tar --zstd -xvf "openwrt-imagebuilder-${{ inputs.version }}-x86-64.Linux-x86_64.tar.zst"

      - name: Build image
        id: build_image
        run: |
          PACKAGES=$(yq '.packages' config.yaml | tr '\n' ' ')
          SIZE=$(yq '.rootfs-size' config.yaml)

          cd "openwrt-imagebuilder-${{ inputs.version }}-x86-64.Linux-x86_64/"
          make image PROFILE="generic" ROOTFS_PARTSIZE="$SIZE" PACKAGES="$PACKAGES"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-${{ inputs.version }}-x86-64-generic-ext4-combined-efi.img.gz
          path: openwrt-imagebuilder-${{ inputs.version }}-x86-64.Linux-x86_64/bin/targets/x86/64/openwrt-*-combined-efi.img.gz
          retention-days: 7

  release:
    name: Release image
    needs: [builder]
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: "*.img.gz"
        merge-multiple: true

    - name: Release
      run: |
        GH_TOKEN=${{ secrets.GH_TOKEN }}

        sha256sum *.img.gz > shasums

        cat > release-notes <<EOF
        **OpenWRT ${{ inputs.tag }}** (homelab image)

        :warning: This image is not intended for a wide audience or production environments :warning:

        **SHA256**
        ```
        $(cat shasums)
        ```
        EOF

        gh release create ${{ inputs.tag }} -F release-notes *.img.gz